import { FILE } from "dns";

export const INJECTION_TOKEN = {
    REDIS_CLIENT: 'REDIS_CLIENT',
    CLOUDINARY: 'CLOUDINARY',

    // Repositories
    USER_REPOSITORY: 'USER_REPOSITORY',
    SESSION_REPOSITORY: 'SESSION_REPOSITORY',
    OAUTH_PROVIDER_REPOSITORY: 'OAUTH_PROVIDER_REPOSITORY',
    ORGANIZATION_REPOSITORY: 'ORGANIZATION_REPOSITORY',
} as const;
