export const INJECTION_TOKEN = {
    REDIS_CLIENT: 'REDIS_CLIENT',
    CLOUDINARY: 'CLOUDINARY',

    // Repositories
    USER_REPOSITORY: 'USER_REPOSITORY',
    SESSION_REPOSITORY: 'SESSION_REPOSITORY',
    OAUTH_PROVIDER_REPOSITORY: 'OAUTH_PROVIDER_REPOSITORY',
    RESTAURANT_REPOSITORY: 'RESTAURANT_REPOSITORY',
    STAFF_REPOSITORY: 'STAFF_REPOSITORY',
    TABLE_REPOSITORY: 'TABLE_REPOSITORY',
    ORDER_REPOSITORY: 'ORDER_REPOSITORY',
    PAYMENT_REPOSITORY: 'PAYMENT_REPOSITORY',
    MENU_CATEGORY_REPOSITORY: 'MENU_CATEGORY_REPOSITORY',
    MENU_ITEM_REPOSITORY: 'MENU_ITEM_REPOSITORY',
} as const;
